on:
  push:
    tags: ['*']
name: Release
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v1
            -
                name: Build
                run: ./gradlew build
